items:
 - STONE_AXE
 - IRON_AXE
 - GOLDEN_AXE
 - DIAMOND_AXE

allowSelfToggle: false
usePerms: true
groupDrops: true
maxVines: 20

treeProtection:
 enabled: true
 message:
  console: true
  chat: false

creative:
 autoCollect: true
 replant: true
 damage: false

trees:
 oak:
  enabled: true
  replant: true
  autoCollect: false
  stump: true
  anyBlock: false
  replantTimer: 0
  leaf:
   reach: 2
   groundOffset: 0
   min: 10
  log:
   min: 4
   max: 50
  drops:
   - OAK_LEAVES,0.01
   - OAK_SAPLING,0.025
   - APPLE,0.005
  damage:
   type: NORM
   amount: 1
 birch:
  enabled: true
  replant: true
  autoCollect: false
  stump: true
  anyBlock: false
  replantTimer: 0
  leaf:
   reach: 2
   groundOffset: 0
   min: 10
  log:
   min: 4
   max: 80
  drops:
   - BIRCH_LEAVES,0.01
   - BIRCH_SAPLING,0.025
  damage:
   type: NORM
   amount: 1
 pine:
  enabled: true
  replant: true
  autoCollect: false
  stump: true
  anyBlock: false
  replantTimer: 0
  leaf:
   reach: 3
   groundOffset: 0
   min: 8
  log:
   min: 4
   max: 200
  drops:
   - SPRUCE_LEAVES,0.01
   - SPRUCE_SAPLING,0.025
  damage:
   type: NORM
   amount: 1
 jungle:
  enabled: true
  replant: true
  autoCollect: false
  stump: true
  anyBlock: false
  replantTimer: 0
  leaf:
   reach: 2
   groundOffset: 0
   min: 10
  log:
   min: 4
   max: 200
  drops:
   - JUNGLE_LEAVES,0.01
   - JUNGLE_SAPLING,0.025
  damage:
   type: NORM
   amount: 1
 acacia:
  enabled: true
  replant: true
  autoCollect: false
  stump: true
  anyBlock: false
  replantTimer: 0
  leaf:
   reach: 3
   groundOffset: 0
   min: 10
  log:
   min: 4
   max: 20
  drops:
   - ACACIA_LEAVES,0.01
   - ACACIA_SAPLING,0.025
  damage:
   type: NORM
   amount: 1
 dark_oak:
  enabled: true
  replant: true
  autoCollect: false
  stump: true
  anyBlock: false
  replantTimer: 0
  leaf:
   reach: 3
   groundOffset: 0
   min: 10
  log:
   min: 4
   max: 200
  drops:
   - DARK_OAK_LEAVES,0.01
   - DARK_OAK_SAPLING,0.025
   - APPLE,0.005
  damage:
   type: NORM
   amount: 1

house:
 - GLASS
 - GLASS_PANE
 - IRON_BARS
 - IRON_TRAPDOOR
 - IRON_DOOR
 - BLACK_STAINED_GLASS
 - BLUE_STAINED_GLASS
 - BROWN_STAINED_GLASS
 - CYAN_STAINED_GLASS
 - GRAY_STAINED_GLASS
 - GREEN_STAINED_GLASS
 - LIGHT_BLUE_STAINED_GLASS
 - LIGHT_GRAY_STAINED_GLASS
 - LIME_STAINED_GLASS
 - MAGENTA_STAINED_GLASS
 - ORANGE_STAINED_GLASS
 - PINK_STAINED_GLASS
 - PURPLE_STAINED_GLASS
 - RED_STAINED_GLASS
 - WHITE_STAINED_GLASS
 - YELLOW_STAINED_GLASS
 - BLACK_STAINED_GLASS_PANE
 - BLUE_STAINED_GLASS_PANE
 - BROWN_STAINED_GLASS_PANE
 - CYAN_STAINED_GLASS_PANE
 - GRAY_STAINED_GLASS_PANE
 - GREEN_STAINED_GLASS_PANE
 - LIGHT_BLUE_STAINED_GLASS_PANE
 - LIGHT_GRAY_STAINED_GLASS_PANE
 - LIME_STAINED_GLASS_PANE
 - MAGENTA_STAINED_GLASS_PANE
 - ORANGE_STAINED_GLASS_PANE
 - PINK_STAINED_GLASS_PANE
 - PURPLE_STAINED_GLASS_PANE
 - RED_STAINED_GLASS_PANE
 - WHITE_STAINED_GLASS_PANE
 - YELLOW_STAINED_GLASS_PANE
 - BLACK_CARPET
 - BLUE_CARPET
 - BROWN_CARPET
 - CYAN_CARPET
 - GRAY_CARPET
 - GREEN_CARPET
 - LIGHT_BLUE_CARPET
 - LIGHT_GRAY_CARPET
 - LIME_CARPET
 - MAGENTA_CARPET
 - ORANGE_CARPET
 - PINK_CARPET
 - PURPLE_CARPET
 - RED_CARPET
 - WHITE_CARPET
 - YELLOW_CARPET
 - OAK_FENCE
 - SPRUCE_FENCE
 - BIRCH_FENCE
 - JUNGLE_FENCE
 - ACACIA_FENCE
 - DARK_OAK_FENCE
 - OAK_FENCE_GATE
 - SPRUCE_FENCE_GATE
 - BIRCH_FENCE_GATE
 - JUNGLE_FENCE_GATE
 - ACACIA_FENCE_GATE
 - DARK_OAK_FENCE_GATE
 - OAK_DOOR
 - SPRUCE_DOOR
 - BIRCH_DOOR
 - JUNGLE_DOOR
 - ACACIA_DOOR
 - DARK_OAK_DOOR
 - OAK_TRAPDOOR
 - SPRUCE_TRAPDOOR
 - BIRCH_TRAPDOOR
 - JUNGLE_TRAPDOOR
 - ACACIA_TRAPDOOR
 - DARK_OAK_TRAPDOOR
version: 3