items:
 - STONE_AXE
 - IRON_AXE
 - GOLD_AXE
 - DIAMOND_AXE
house:
 - GLASS
 - STAINED_GLASS
 - THIN_GLASS
 - STAINED_GLASS_PANE
 - FENCE
 - NETHER_FENCE
 - SPRUCE_FENCE
 - BIRCH_FENCE
 - DARK_OAK_FENCE
 - ACACIA_FENCE
 - JUNGLE_FENCE
 - FENCE_GATE
 - SPRUCE_FENCE_GATE
 - BIRCH_FENCE_GATE
 - DARK_OAK_FENCE_GATE
 - ACACIA_FENCE_GATE
 - JUNGLE_FENCE_GATE
 - IRON_FENCE
 - TRAP_DOOR
 - IRON_TRAPDOOR
 - WOODEN_DOOR
 - IRON_DOOR_BLOCK
 - SPRUCE_DOOR
 - BIRCH_DOOR
 - JUNGLE_DOOR
 - ACACIA_DOOR
 - DARK_OAK_DOOR
 - CARPET

allowSelfToggle: false
usePerms: true
groupDrops: true
maxVines: 20

treeProtection:
 enabled: true
 message:
  console: true
  chat: false

creative:
 autoCollect: true
 replant: true
 damage: false

trees:
 oak:
  enabled: true
  replant: true
  autoCollect: false
  stump: true
  anyBlock: false
  replantTimer: 0
  leaf:
   reach: 2
   groundOffset: 0
   min: 10
  log:
   min: 4
   max: 50
  drops:
   - LEAVES,0.01
   - SAPLING,0.025
   - APPLE,0.005
  damage:
   type: NORM
   amount: 1
 birch:
  enabled: true
  replant: true
  autoCollect: false
  stump: true
  anyBlock: false
  replantTimer: 0
  leaf:
   reach: 2
   groundOffset: 0
   min: 10
  log:
   min: 4
   max: 80
  drops:
   - LEAVES,0.01
   - SAPLING,0.025
  damage:
   type: NORM
   amount: 1
 pine:
  enabled: true
  replant: true
  autoCollect: false
  stump: true
  anyBlock: false
  replantTimer: 0
  leaf:
   reach: 3
   groundOffset: 0
   min: 8
  log:
   min: 4
   max: 200
  drops:
   - LEAVES,0.01
   - SAPLING,0.025
  damage:
   type: NORM
   amount: 1
 jungle:
  enabled: true
  replant: true
  autoCollect: false
  stump: true
  anyBlock: false
  replantTimer: 0
  leaf:
   reach: 2
   groundOffset: 0
   min: 10
  log:
   min: 4
   max: 200
  drops:
   - LEAVES,0.01
   - SAPLING,0.025
  damage:
   type: NORM
   amount: 1
 acacia:
  enabled: true
  replant: true
  autoCollect: false
  stump: true
  anyBlock: false
  replantTimer: 0
  leaf:
   reach: 3
   groundOffset: 0
   min: 10
  log:
   min: 4
   max: 20
  drops:
   - LEAVES,0.01
   - SAPLING,0.025
  damage:
   type: NORM
   amount: 1
 dark_oak:
  enabled: true
  replant: true
  autoCollect: false
  stump: true
  anyBlock: false
  replantTimer: 0
  leaf:
   reach: 3
   groundOffset: 0
   min: 10
  log:
   min: 4
   max: 200
  drops:
   - LEAVES,0.01
   - SAPLING,0.025
   - APPLE,0.005
  damage:
   type: NORM
   amount: 1

version: 2