name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}

description: ${project.description}
author: gorbb
website: ${project.url}

softdepend: [CoreProtect]

commands:
 qt:
  description: QwickTree admin/debug command
  aliases: [qwicktree]
  usage: Try /<command> for help.

permissions:
 qwicktree.*:
  description: Gives complete access to QwickTree
  children:
   qwicktree.chop: true
   qwicktree.notify: true
   qwicktree.debug: true
   qwicktree.reload: true
   qwicktree.info: true
   qwicktree.bypass: true
   qwicktree.toggle.*: true
  qwicktree.toggle.*:
   children:
    qwicktree.toggle.self: true
    qwicktree.toggle.others: true
    qwicktree.toggle.all: true
    qwicktree.toggle.list: true
  qwicktree.chop:
   description: Allows players to use QwickTree to chop down trees
   default: true
  qwicktree.notify:
   description: Lets players get a notification if a 'house' block is detected near a tree.
   default: op
  qwicktree.debug:
   description: Allows a player access to the debugger
   default: op
  qwicktree.reload:
   description: Allows a player to reload the config
   default: op
  qwicktree.info:
   description: Allows a player to view information on the trees chopped since the last reload.
   default: op
  qwicktree.bypass:
   description: Allows a player to add bypasses from the 'house' blocks for any player.
   defualt: op
  qwicktree.toggle.self:
   description: Allows a player to toggle the plugin enabled or disabled for themselves.
   default: op
  qwicktree.toggle.others:
   description: Allows a player to toggle the plugin enabled or disabled for any other players on the server. This permission implies qwicktree.toggle.self
   default: op
  qwicktree.toggle.all:
   description: Allows the player to globally enable or disable the plugin for every player on the server.
   default: op
  qwicktree.toggle.list:
   description: Lets the player see and clear the list of players for who the plugin is disabled for.
   default: op