name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}

description: ${project.description}
author: gorbb
website: ${project.url}

# I'll do commands later